### ISSUE TITLE
Settings tab modified to properties

### ISSUE THREAD

**Issue by rajesh3699** [micro-ROS/micro_ros_stm32cubemx_utils#102]
The settings tab under project section in CubeMxIDE has been changes to properties. This is a small change but may help new peeps

**Comment by pablogs9** [comment]
Could you open a PR?

**Comment by rajesh3699** [comment]
Done!

**Comment by pablogs9** [comment]
https://github.com/micro-ROS/micro_ros_stm32cubemx_utils/pull/103
