### ISSUE TITLE
publishing 3rd message fails

### ISSUE THREAD

**Issue by DrMarkusKrug** [micro-ROS/micro_ros_stm32cubemx_utils#111]
Hi,
I have setup an FreeRTOS application that is publishing 3 (multirarray) messages in 3 different tasks.
My micro ros agent is displaying all of the topics with 'ros2 topic list'. However one of them is not giving an echo. I can always echo only 2 out of the 3 and I can change the 2 in any combination (msg1+msg2, msg1+msg3 or msg2+msg3). 
The call rcl_publish() is returning with RCL_RET_OK for the call that leads to the missing echo.
I already changed in the file colcon-embeddedrtps.meta file the parameter DERTPS_MAX_PUBLISHERS=10 but with no success so far.
Any hint?

Best Regards
Markus

**Comment by pablogs9** [comment]
micro-ROS by default are not thread-safe so, are you locking your micro-ROS calls between threads?

Also, could you share a micro-ROS Agent log output with the `-v6` flag enabled?

**Comment by DrMarkusKrug** [comment]
Hi,

I changed the starting time for the three tasks that are doing the publishing to a sequence with a few milliseconds delay between them. That seems to solve the problem. Therefore I think you comment about thread-safety might be the root cause. Do you have an idea how to fix that? As far as I can see from the log output each published message is acknowledged by the agent. Maybe a semaphore that is locked just before publishing and unlocked after receiving the acknowledgement might be a good idea. Or is there a ROS API call to setup a callback after the acknowledgement message?
Best Regards
Markus

**Comment by pablogs9** [comment]
Yes, it shall be enough to lock with a mutex/semaphore the access to rclc/rcl calls.

I'm closing since solved.
