### ISSUE TITLE
Problem with prebuild step in CubeIDE under win11

### ISSUE THREAD

**Issue by elgarbe** [micro-ROS/micro_ros_stm32cubemx_utils#126]
Hi, I'm working on windows 11, I have docker desktop installed. I follow the steps to configure cubeIDE, but I get an error when I've tried to build:

```
09:13:05 **** Build of configuration Debug for project microROS_Pub ****
make -j20 all 
docker pull microros/micro_ros_static_library_builder:humble && docker run --rm -v D:\elgarbe\ws_ARM\ws_micro_ROS\microROS_Pub:/project --env MICROROS_LIBRARY_FOLDER=micro_ros_stm32cubemx_utils/microros_static_library_ide microros/micro_ros_static_library_builder:humble
humble: Pulling from microros/micro_ros_static_library_builder
Digest: sha256:3c13fee7e7d6814ebc87c7ccd4c5d7592310b8adc86c5ff2a1f4de179776a0fb
Status: Image is up to date for microros/micro_ros_static_library_builder:humble
docker.io/microros/micro_ros_static_library_builder:humble
docker: Error response from daemon: El sistema no puede encontrar el archivo especificado.
See 'docker run --help'.
make[1]: *** [makefile:91: pre-build] Error 125
make: *** [makefile:64: all] Error 2
"make -j20 all" terminated with exit code 2. Build might be incomplete.
``` 
So, I open a terminal in the project location and run docker pull microros/micro_ros_static_library_builder:humble and then run 
docker run --rm -v D:\elgarbe\ws_ARM\ws_micro_ROS\microROS_Pub:/project --env MICROROS_LIBRARY_FOLDER=micro_ros_stm32cubemx_utils/microros_static_library_ide microros/micro_ros_static_library_builder:humble
and everithing works as expected. I remove prebuild step in my project and build it. Then the project is flashed and working ok.
Is there a way to solve this prebuild step problem?

**Comment by pablogs9** [comment]
Hello, this repository has not been tested in Windows. 

Please if you find a workaround to configure the prebuild steps on Windows contribute it to the documentation with a PR.

**Comment by elgarbe** [comment]
Done, let me know if it is ok for you to merge

**Comment by pomelo925** [comment]
same issue and @elgarbe way helps, tks a lot
