### ISSUE TITLE
is micro_ros_utilities_create_message_memory available?

### ISSUE THREAD

**Issue by elgarbe** [micro-ROS/micro_ros_stm32cubemx_utils#132]
Hi, I've read [this](https://micro.ros.org/docs/tutorials/advanced/handling_type_memory/) and would like to use micro_ros_utilities_create_message_memory, but it seems that it's not available on libmicroros. 

Thank

**Comment by pablogs9** [comment]
Add it to extra packages: https://github.com/micro-ROS/micro_ros_stm32cubemx_utils/tree/iron#adding-custom-packages

**Comment by elgarbe** [comment]
So, I need to clone [this repo](https://github.com/micro-ROS/micro_ros_utilities) into microros_static_library/library_generation/extra_packages/ folder and rebuild the library?

**Comment by pablogs9** [comment]
Yes

**Comment by elgarbe** [comment]
I recompile the library but now I have a new error:

```
//  Assigning dynamic memory to the frame_id char sequence
	IMU_msg.header.frame_id.capacity = 10;	// 9 for "base_link" + 1 for null terminated string???
	IMU_msg.header.frame_id.data = (char*) malloc(IMU_msg.values.capacity * sizeof(char));
	IMU_msg.header.frame_id.size = 0;

	// Assigning value to the frame_id char sequence
	strcpy(IMU_msg.header.frame_id.data, "base_link");
	IMU_msg.header.frame_id.size = strlen(IMU_msg.header.frame_id.data);

```
IMU_msg is a Vecto3Stamped type. I don't fully understand capacity and size fields of header.frame. 
The error is on `(char*) malloc(IMU_msg.values.capacity * sizeof(char))`;
`'geometry_msgs__msg__Vector3Stamped' has no member named 'values'`

Thank for the help!

**Comment by pablogs9** [comment]
Those concepts are explained here: https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/memory_management/memory_management.html#message-memory

**Comment by elgarbe** [comment]
Let me see if I understand correctly:
IMU_msg.header is a compund data type it's members are stamp and frame_id. 
frame_id is a sequence data type (a sequence of chars) and thereare for it has capacity, data and size members.
I don't fully understand this:
"The pointer should have memory for storing up to capacity values and size member shows how many element are currently in the sequence"

maybe I could understand with an example. If I want to store "base_link" on data member, then I have to use:
`IMU_msg.header.frame_id.capacity = 10;` becouse I need the null symbol as string termination, right?
then I need to reserve memory for the data member:
`IMU_msg.header.frame_id.data = (char*) malloc(IMU_msg.header.frame_id.capacity * sizeof(char));`
next I can fill data member with:
`strcpy(IMU_msg.header.frame_id.data, "base_link");`
here I'm not sure about the static string "base_link" and the null terminated frame_id.data
Finally I should use `IMU_msg.header.frame_id.size = strlen(IMU_msg.header.frame_id.data);`
am I right? or do I miss something?

**Comment by pablogs9** [comment]
That's it

**Comment by elgarbe** [comment]
Ok and I can replace that code with this:
```

	static micro_ros_utilities_memory_conf_t conf = {0};
	bool success = micro_ros_utilities_create_message_memory(
		ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs, msg, Vector3Stamped),
		&IMU_msg,
		conf
		);
	IMU_msg.header.frame_id = micro_ros_string_utilities_set(IMU_msg.header.frame_id, "base_link");
	if (success)
		printf("[INFO] imu msg init OK!\r\n");
	else
	{
		printf("[ERROR]imu msg init failed!\r\n");
```
using micro_ros_utilities, right?

**Comment by pablogs9** [comment]
It should be possible, yes

**Comment by elgarbe** [comment]
Thank a lot for the help!
