### ISSUE TITLE
simple publisher/subscriber example

### ISSUE THREAD

**Issue by elgarbe** [micro-ROS/micro_ros_stm32cubemx_utils#16]
Hi, I've already create a new stm32cubeIDE project with foxy branch. I've configured UART with DMA, enabled freeRTOS.
Now I would like to add minimum working code in order to make a publisher and a subscriber. Is there some guide about it?

thank

**Comment by pablogs9** [comment]
[Here](https://github.com/micro-ROS/micro_ros_stm32cubemx_utils/blob/galactic/sample_main.c) you have some demo code. Just use it in your main application.

<
