### ISSUE TITLE
Ethernet support for STM32CubeIDE

### ISSUE THREAD

**Issue by Rob-le-Houe** [micro-ROS/micro_ros_stm32cubemx_utils#19]
Is it possible to use the ethernet udp transport method when using this library? Do you have an example of the .ioc parameters for ethernet using the olimex-e407? 

Many Thanks

**Comment by pablogs9** [comment]
Hello, this is not a planned feature in the micro-ROS team right now. Let us know if you want to contribute it.

**Comment by DaniGarciaLopez** [comment]
I'm also interested on using the Olimex-e407 with Ethernet as the transport layer. Have there been any recent developments in this area? Are there any examples or suggestions on where to begin?
