### ISSUE TITLE
micro-ROS agent does not initialize any communication

### ISSUE THREAD

**Issue by jdgg98** [micro-ROS/micro_ros_stm32cubemx_utils#60]
Hello, I've been trying to setup micro-ROS on a STM32F407VGT6 microcontroller. I'm using ROS2's foxy distro, FreeRTOS and micro_ros_stm32cubemx_utils. I though I was almost done with a simple publisher example, but when I start the micro-ros-agent it seems like it is not able to initialize any communication with the publisher on my microcontroller. This is the result a I get:

![error](https://user-images.githubusercontent.com/44977262/167937090-49e0b7c3-5f82-436f-952a-6def80b0476d.png)

Does anyone have a clue about what might be wrong?

**Comment by pablogs9** [comment]
Can you check in your MCU UART port if something is being written using a tool such as miniterm or minicom.

If your micro-ROS client is behaving correctly, some bytes should be being written in `/dev/ttyACM0`

**Comment by pablogs9** [comment]
Any update on this? @jdgg98

**Comment by jdgg98** [comment]
Hi! I used minicom as you told me and it seems that nothing is being written in `/dev/ttyACM0`. I also found out that I might have made some mistakes in the FreeRTOS and UART configurations in STMCubeMX, so I will fix them and try again.

**Comment by pablogs9** [comment]
Any update?

**Comment by jdgg98** [comment]
At the end it turns out that microROS is not compatible with the firmware library I am using, so I had to discard the use of microROS.

**Comment by do-coding-J** [comment]
I've got something on minicom with /dev/ttyACM0 but micro ros agent can't find my board
