### ISSUE TITLE
How can I increase the publishing hertz?

### ISSUE THREAD

**Issue by Interactics** [micro-ROS/micro_ros_stm32cubemx_utils#72]
# Setup

Board - NUCLEO STM32-F429ZI 
RTOS - FreeRTOS
Communication - through UART - 921600bps (115.2KB/s)

Target Topic publishing speed = 250Hz
Present = 125Hz 

### HZ information
```
average rate: 124.997
	min: 0.005s max: 0.011s std dev: 0.00013s window: 10000
```

### Bandwidth (bw imu_topic)
```
39.68 KB/s from 100 messages
	Message size mean: 0.32 KB min: 0.32 KB max: 0.32 KB
```

# Code

### code 

```  
rclc_publisher_init_best_effort(
        &imu_publisher,
        &node,
        ROSIDL_GET_MSG_TYPE_SUPPORT(sensor_msgs, msg, Imu),
        "imu_pub");

TickType_t xLastWakeTime = xTaskGetTickCount();
for (;;) {
  LL_GPIO_TogglePin(LD3_GPIO_Port, LD3_Pin); // Hz Test for oscilloscope
  rcl_ret_t rc = rcl_publish(&imu_pub, &imu_msg, NULL);
  vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(2));
}
```

# Question 

When I checked LD3Pin with oscilloscope, I confirmed that it's publishg frequency is exactly 125Hz.

To increase pubilshing Hz, I think I need to modify Micro-ROS's QoS setting. 
But I cannot find ```app-colcon.meta``` in micro_ros_stm32cubemx_utils

[https://micro.ros.org/docs/tutorials/advanced/create_dds_entities_by_ref/](url)

Is it right to speed up publishing Hz by changing the QoS settings?
If correct, which file is in charge of it?

**Comment by pablogs9** [comment]
Try to publish a basic type such as `std_msgs/Int32` with the same code. If this one reaches the desired rate, that means that your message is too big for the desired rate and the actual throughput of your transport.

**Comment by pablogs9** [comment]
Some approx calculations: 

```
sensor_msgs/Imu has header + 27 + 4  + 3 + 3 float64 -> aprox 37 float64 -> 296 B each msg

if you send a 500 Hz you will need to send 296 B/msg * 500 msg/s = 148000 B/s = 148 kB/s

your transport only provides 115.2 kB/s
```

**Comment by Interactics** [comment]
Thank you for your reply. :)

Sorry. there is a little mistake in my code 

```  vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(2));``` ->   ```vTaskDelayUntil(&xLastWakeTime, pdMS_TO_TICKS(4));```

So, I need 250Hz.

Before you mentioned it, I've already calculated.
In my case, the requirement Byte/s is approximately under 100kB and data publishing frequency is 125Hz.

As you said, I think the official imu message size is so big that it's hard to send quickly.
I'll change the message to a lighter custom message.
