### ISSUE TITLE
cannot find -lmicroros 

### ISSUE THREAD

**Issue by SNoDIVA** [micro-ROS/micro_ros_stm32cubemx_utils#83]
Hi there,
I have some problems when I follow the tutorial to port to STM32CubeIDE. The following error message is encountered after 
`add microros in Libraries (-l)`

Error message:
`/opt/st/stm32cubeide_1.8.0/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.9-2020-q2-update.linux64_2.0.0.202105311346/tools/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: cannot find -lmicroros`

OS : ubuntu 20.04 LTS
ROS2 version : Foxy
STM32CubeIDE version : 1.8.0

Board : ST Nucleo F446RE

What do I need to set up to solve this problem?

Thx.

**Comment by pablogs9** [comment]
Can you check if `libmicroros.a` has been generated in your project directory tree?

**Comment by SNoDIVA** [comment]
Hi,
It has been checked, and`libmicroros.a` is generated, I have also tried to change `add microros in Libraries (-l)` to `libmicroros`, the same error message.

![image](https://user-images.githubusercontent.com/20574786/199915606-0b7d8307-5b0e-49d8-911f-914865f4142c.png)

Thx

**Comment by pablogs9** [comment]
Make sure that in the step of adding the library you are adding just the path to `-L`

**Comment by SNoDIVA** [comment]
Hi,
I checked again, make sure to add the 'microros_static_library_ide/libmicroros/include' path in '-L'.

`MCU GCC Linker`->`Include paths`:
![image](https://user-images.githubusercontent.com/20574786/199920699-b9756b44-ffe5-4df6-b171-60fd6598bb10.png)

`MCU GCC Linker`->`Libraries`:
![image](https://user-images.githubusercontent.com/20574786/199920733-66f15c20-d16c-4127-8f09-17279e716214.png)

Thx.

**Comment by pablogs9** [comment]
The library is not in `<ABSOLUTE_PATH_TO>/micro_ros_stm32cubemx_utils/microros_static_library_ide/libmicroros/include`, it is in `<ABSOLUTE_PATH_TO>/micro_ros_stm32cubemx_utils/microros_static_library_ide/libmicroros`

Please read the instructions carefully

**Comment by SNoDIVA** [comment]
Hi,
OK, so I didn't see it clearly. Compile passed. Thanks a lot for help.

Thx.
