### ISSUE TITLE
[Simple Subscriber]: : undefined reference to `usleep`

### ISSUE THREAD

**Issue by MingshanHe** [micro-ROS/micro_ros_stm32cubemx_utils#88]
Hi~
I try to make a simple subscriber to get the data from the PC and I include the <unistd.h>.
When I try to `rclc_executor_spin_one_period(&executor,1000);` in the `for` loop, the error happens with `undefined reference to usleep`
How can I solve this?

**Comment by pablogs9** [comment]
Probably you will need to implement a usleep function or implement [here](https://github.com/ros2/rclc/blob/master/rclc/src/rclc/sleep.c) a sleep implementation for your platform.

AFAIK `rclc_executor_spin_some` does not rely on usleep, could you use this one instead?
