### ISSUE TITLE
Multi service creation problem

### ISSUE THREAD

**Issue by randdEngineer** [micro-ROS/micro_ros_stm32cubemx_utils#94]
Hello,
I'm using NUCLEO-F446ZE board and STM32CubeIDE environment. When i try to create second service i get this message:
"failed status on line 313: 1. aborting."
Here is line 313:
RCCHECK(rclc_service_init_default(&motorCommandService, &node, ROSIDL_GET_SRV_TYPE_SUPPORT(trion_interface, srv, MotorCommand), "motor_command"));

**Comment by pablogs9** [comment]
Have you increased this: 
https://github.com/micro-ROS/micro_ros_stm32cubemx_utils/blob/3a479bc9fdf68b5bce6b4d097d196470241907ab/microros_static_library_ide/library_generation/colcon.meta#L46
?

**Comment by randdEngineer** [comment]
After increasing it worked. Thanks.
