### ISSUE TITLE
 Need to create custom  massage/service 

### ISSUE THREAD

**Issue by hishambaharom** [micro-ROS/micro_ros_stm32cubemx_utils#97]
I would like to create custom massage/service how I can make it, what the step require.

**Comment by pablogs9** [comment]
Please read the documentation: 

https://github.com/micro-ROS/micro_ros_stm32cubemx_utils#adding-custom-packages
https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/custom_types/custom_types.html

**Comment by hishambaharom** [comment]
Still don't get it,   I have create the custom service in my uros_ws  all ok but, what folder I need to copy to microros_static_library/library_generation/extra_packages/  and what to add/write to  /microros_static_library/library_generation/extra_packages/extra_packages.repos or so it can call when I build using stm32cube ide

**Comment by pablogs9** [comment]
`ros2 pkg create --build-type ament_cmake my_custom_message` creates a new ROS 2 package where you will define your new message. This is the folder that you need to place in `extra_packages`
